---
title: "Bird Classifier Requirement Analysis"
date: "`r Sys.Date()`"
author: "Peter Aichinger-Frankhauser, Jens Barkshat, Robert Bartz, Michael Holzinger, Elias Reckmeyer & Viviane Aicher"
output:
  rmdformats::robobook:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---


# Anforderungen und Aufgaben Lukas Huber:

1. 
>>>>>>>>>>>>>>>>>
Finden Sie Veränderungen der Requirements für Ihr System, die
wahrscheinlich eintreten könnten:
- Veränderung des Daten-liefernden Systems
- Mehrere Standorte/Formate/Systeme/Umstände mit denen Ihr System
umgehen können „soll“/“muss“
<<<<<<<<<<<<<<<<<

2.
>>>>>>>>>>>>>>>>>><<
Welche Web-Technologien braucht Ihr Data Science System?
- z.B. eine App, mit Server im Hintergrund,
- z.B. eine Schnittstelle, für andere Webseiten,...
- Welche Modelle, Datenbanken, Technologien möchte/sollte man einsetzen? Wo/Wie wird
gespeichert?
<<<<<<<<<<<<<<<<<<

3.
>>>>>>>>>>>>>>>>>>
- Entwickeln Sie ein einfaches Architekturmodellfür Ihren Use Case!
- Welche Architektur würden Sie  wählen, warum?
- Welche Art von Schnittstellen wären notwendig? Welche denkbar? Welche möglich?
- Wie können Sie „Messaging“ nutzen?
- Welche Informationen können Sie aus „Log“-Dateien extrahieren?
- Wie könnten Sie über „Internationalisierung stolpern“ – (nicht nur Kunden aus diversen Ländern)?
<<<<<<<<<<<<<<<<<

4.
>>>>>>>>>>>>>>>>>
- README.md
- Requirements/
- my_requirement diagram
- My_requirement „writing“
- Architecture/
- Architecture content
- Design
- Design content
- + Fiktive Umsetzung (z.b. .gitlab-ci.yml, test.py,…)
- + Verwendung von Git-Versionierung, Branches, Tags.
<<<<<<<<<<<<<<<<

5.
>>>>>>>>>>>>>>>>>>>>>>
- Entwerfen Sie ihr (hypothetisches) Entwicklungsmodell (Vorgehen) – für Ihr
Beispiel
- Beschreiben Sie dazu, wie Sie vorgehen
- Setzen Sie es ggf. „demonstrativ“ um.
- Entwerfen Sie die Systemarchitektur (Client-Server, Monolith, Micro?)
- Modellieren Sie relevante Sichten auf das System
- Welche Tests sind sinnvoll – schreiben Sie einen (auch fiktiven) Test!
- Welche Logs sind notwendig? – Beschreiben Sie Beispiele
- Benötigt ihr Projekt Internationalisierung? Wo?
- Welche APIs könnten Sie verwenden/anbieten?
- Welche Design Patterns können Sie Verwenden?
- Wie könnte eine CI/CD-Pipeline aussehen?
-Spielen sie die Pipeline für die Entw. Eines Features durch!
<<<<<<<<<<<<<<<<<<<

6. Übernimmt Michael Holzinger
>>>>>>>>>>>>>>>>>>>
- Welche Art von Data-Science-Architektur würde für Ihr Projekt passen?
- Wie könnte diese aussehen?
- Warum nicht ein anderer Ansatz?
- Wie könnten Pipelines Verwendung finden?
<<<<<<<<<<<<<<<<<<<


# 1. INTRODUCTION

Ever seen a bird in your garden and wondered what kind of bird it is? 
Now you can simply let AI classify your bird. Just take a picture of it and upload it to our webpage. The algorithm will tell you what kind of bird it is. (Currently only 3 kinds of birds will be detected).

## 1.1 PURPOSE

The aim of the project is to build a webpage where users can upload their bird pictures in order to classify them.
At first only three categories of birds will be detected: Great tit, robin and sparrow.

## 1.2 INTENDED AUDIENCE

Everybody who loves nature and has a gitHub account...

## 1.3 INTENDED USE

Just for fun...

## 1.4 SCOPE

Specification including benefits, objectives, and goals.

## 1.5 DEFINITIONS AND ACRONYMS

Risk of false detection, failing upload, wrong picture formats...



# 2. OVERALL DESCRIPTION

## 2.1 USER NEEDS


## 2.2 ASSUMPTIONS AND DEPENDENCIES



# 3. SYSTEM FEATURES AND REQUIREMENTS

Overview 

## 3.1 FUNCTIONAL REQUIREMENTS

## 3.2 TECHNICAL REQUIREMENTS

## 3.3 QUALITY OF SERVICE REQUIREMENTS

## 3.4 USER INTERFACE REQUIREMENTS

## 3.5 EXTERNAL INTERFACE REQUIREMENTS

## 3.6 EXTERNAL DELIVERABLE/INTERFACE REQUIREMENTS

## 3.7 ACTIVITY REQUIREMENTS

## 3.8 SECURITY REQUIREMENTS

## 3.9 LEGAL & CONTRACT REQUIREMENTS



# 4. Data Science Methodology


# 5. Graphs


# 6. Web Technologies


# 7. Data Science Architecture


# 4. APPROVAL

Approval by key stakeholders is needed after the definition of the requirements.